#!/usr/bin/env node

'use strict';

var fs = require('fs');

fs.writeFileSync(process.argv[3], read(process.argv[2]).replace(
  /[(]include :language ([^ ]*) ([^)]*)[)]/g,
  function(_, language, filename) {
    return [
      '<pre>',
      '<code class="language-', language, '">',
      require('../lib/decorate/' + language)(read(filename), '', []),
      '</code>',
      '</pre>',
    ].join('');
  }
).replace(
  /[(]code-block :language ([^)]*)[)]\n([\s\S]*?)[ ]*[(]end-code-block[)]/g,
  function(_, language, input) {
    var indent = /^[ ]*/.exec(input)[0].length;
    return [
      '<pre>',
      '<code class="language-', language, '">',
      require('../lib/decorate/' + language)(input.replace(new RegExp('^[ ]{' + indent + '}', 'gm'), ''), '', []),
      '</code>',
      '</pre>',
    ].join('');
  }
));

// read :: String -> String
function read(filename) {
  return fs.readFileSync(filename, {encoding: 'utf8'});
}
